// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EducationColumns holds the columns for the "education" table.
	EducationColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
	}
	// EducationTable holds the schema information for the "education" table.
	EducationTable = &schema.Table{
		Name:       "education",
		Columns:    EducationColumns,
		PrimaryKey: []*schema.Column{EducationColumns[0]},
	}
	// InstitutionColumns holds the columns for the "institution" table.
	InstitutionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "education_institution", Type: field.TypeInt, Nullable: true},
	}
	// InstitutionTable holds the schema information for the "institution" table.
	InstitutionTable = &schema.Table{
		Name:       "institution",
		Columns:    InstitutionColumns,
		PrimaryKey: []*schema.Column{InstitutionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "institution_education_institution",
				Columns:    []*schema.Column{InstitutionColumns[2]},
				RefColumns: []*schema.Column{EducationColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EducationTable,
		InstitutionTable,
	}
)

func init() {
	EducationTable.Annotation = &entsql.Annotation{
		Table: "education",
	}
	InstitutionTable.ForeignKeys[0].RefTable = EducationTable
	InstitutionTable.Annotation = &entsql.Annotation{
		Table: "institution",
	}
}
