// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Education is the predicate function for education builders.
type Education func(*sql.Selector)

// Institution is the predicate function for institution builders.
type Institution func(*sql.Selector)
